akka {
  loglevel = DEBUG
  log-config-on-start = "on"
}

http {
  interface = "0.0.0.0"
  port = 9000
}


akka.http.server {
  request-timeout = 60s
}


databricks {

 warehouse {
  jdbc = "jdbc:databricks://e2-demo-field-eng.cloud.databricks.com:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/862f1d757f0424f7"
  jdbc = ${?jdbc}
  token = ""
  token = ${?token}
 }

 data {
  catalog = "hls_healthcare"
  catalog = ${?catalog}
  schema = "databricks_fhir_service_forked"
  schema = ${?schema}
 }	
}
