akka {
  loglevel = DEBUG
  loglevel = ${?loglevel}
  log-config-on-start = "on"
  log-config-on-start = ${?log-config-on-start}
}

http {
  interface = "0.0.0.0"
  interface =${?interface}
  port = 9000
  port = ${?port}
}


akka.http.server {
  request-timeout = 60s
  request-timeout = ${?request-timeout}
}



databricks {

 warehouse {
  jdbc = "jdbc:databricks://e2-demo-field-eng.cloud.databricks.com:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/a83cea705d53cb62;"
  jdbc = ${?jdbc}
  token = "dapi19889cf10392538698dfa01cfc660baa"
  token = ${?token}
 }

 data {
  catalog = "hls_healthcare"
  catalog = ${?catalog}
  schema = "databricks_fhir_service_forked"
  schema = ${?schema}
 }	
}
