akka {
  loglevel = DEBUG
  loglevel = ${?loglevel}
  log-config-on-start = "on"
  log-config-on-start = ${?log-config-on-start}
}

http {
  interface = "0.0.0.0"
  interface =${?interface}
  port = 9000
  port = ${?port}
}


akka.http.server {
  request-timeout = 60s
  request-timeout = ${?request-timeout}
}


databricks {
 warehouse {
  jdbc = "jdbc:databricks://e2-demo-field-eng.cloud.databricks.com:443/default;transportMode=http;ssl=1;AuthMech=3;httpPath=/sql/1.0/warehouses/862f1d757f0424f7"
  jdbc = ${?jdbc}
  token = ""
  token = ${?token}
 }

 data {
  catalog = "hls_healthcare"
  catalog = ${?catalog}
  schema = "databricks_fhir_service_forked"
  schema = ${?schema}
 }	

 alias {
   sqlpredicate {
    subject = "subject.reference"
    #id = "fhir_id"
   }
   dollareverything {
    #prefix = "Patient/"
    prefix = "urn:uuid:"
   }
 }
}

api.jdbc {
  hikari { 
    connectionRetries = 1
    connectionRetries = ${?connectionRetries}
    queryRetries = 1
    queryRetries = ${?queryRetries}
    minIdle = 1
    minIdle = ${?minIdle}
    maxPoolSize = -1 #defaults to 2x # of CPUs when <= 0
    maxPoolSize = ${?maxPoolSize}
    timeoutMS = 30000
    timeoutMS = ${?timeoutMS}
  }
}

