package com.databricks.industry.solutions.fhirapi

import java.sql.{Connection, DriverManager, ResultSet}
import org.joda.time.DateTime
import java.util.{Date, UUID}

class QueryRunner (ds: DataStore, queryRetries: Int = 1){

  // method to run the query
  def runQuery(queryInput: QueryInput): QueryOutput = {
    val queryStartTime = DateTime.now
    val r = ds.execute(queryInput.query, queryRetries,ds.getConnection) //returns a tuple of data (Map[String,String], Option(String))
    QueryOutput(r(0), System.currentTimeMillis() - queryStartTime.getMillis, queryStartTime, r(1), queryInput.query)

  }
}

case class QueryInput(query: String)

case class QueryOutput(val queryResults: List[Map[String, String]], val queryRuntime: Long,val  queryStartTime: DateTime,val  error: Option[String], queryInput: String){
  override def toString : String = {
    "queryRuntime (in ms): " + queryRuntime +
    "\nqueryStartTime: " + queryStartTime +
    "\nqueryError: " + error.toString +
    "\nnumRows: " + queryResults.length + 
    "\nqueryExecuted: " + queryInput
 }
}

case class FormattedOutput(queryOutput: QueryOutput, bundle: String)

object FormattedOutput{

  //TODO for Liburna
  def fromQueryOutputSearch(queryOutput: QueryOutput): FormattedOutput = {
    ???

    /*
     match length(queryResults)
     case 0 => return empty bundle
     case _ => return populated bundle
     queryResult = list of 1 item ["Patient", -> 
     {"id":"a62a41dc-5ac1-ff47-3fc5-08f6ad045571","meta":{"profile":["http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"]},"text":{"status":"generated","div":"<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: master-branch-latest\n .   Person seed: 2256694784849346412  Population seed: 1649789466584</div>"},"extension":["{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-race\",\"extension\":[{\"url\":\"ombCategory\",\"valueCoding\":{\"system\":\"urn:oid:2.16.840.1.113883.6.238\",\"code\":\"2106-3\",\"display\":\"White\"}},{\"url\":\"text\",\"valueString\":\"White\"}]}","{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity\",\"extension\":[{\"url\":\"ombCategory\",\"valueCoding\":{\"system\":\"urn:oid:2.16.840.1.113883.6.238\",\"code\":\"2186-5\",\"display\":\"Not Hispanic or Latino\"}},{\"url\":\"text\",\"valueString\":\"Not Hispanic or Latino\"}]}","{\"url\":\"http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName\",\"valueString\":\"Jen DuBuque\"}","{\"url\":\"http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex\",\"valueCode\":\"M\"}","{\"url\":\"http://hl7.org/fhir/StructureDefinition/patient-birthPlace\",\"valueAddress\":{\"city\":\"Haverhill\",\"state\":\"Massachusetts\",\"country\":\"US\"}}","{\"url\":\"http://synthetichealth.github.io/synthea/disability-adjusted-life-years\",\"valueDecimal\":0.13890250859511097}","{\"url\":\"http://synthetichealth.github.io/synthea/quality-adjusted-life-years\",\"valueDecimal\":66.86109749140489}"],"identifier":[{"system":"https://github.com/synthetichealth/synthea","value":"a62a41dc-5ac1-ff47-3fc5-08f6ad045571"},{"type":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/v2-0203","code":"MR","display":"Medical Record Number"}],"text":"Medical Record Number"},"system":"http://hospital.smarthealthit.org","value":"a62a41dc-5ac1-ff47-3fc5-08f6ad045571"},{"type":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/v2-0203","code":"SS","display":"Social Security Number"}],"text":"Social Security Number"},"system":"http://hl7.org/fhir/sid/us-ssn","value":"999-68-1475"},{"type":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/v2-0203","code":"DL","display":"Driver's License"}],"text":"Driver's License"},"system":"urn:oid:2.16.840.1.113883.4.3.25","value":"S99975486"},{"type":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/v2-0203","code":"PPN","display":"Passport Number"}],"text":"Passport Number"},"system":"http://standardhealthrecord.org/fhir/StructureDefinition/passportNumber","value":"X17850816X"}],"name":[{"use":"official","family":"Herzog","given":["Jorge"],"prefix":["Mr."]}],"telecom":[{"system":"phone","value":"555-792-7721","use":"home"}],"gender":"male","birthDate":"1954-10-13","address":[{"extension":["{\"url\":\"http://hl7.org/fhir/StructureDefinition/geolocation\",\"extension\":[{\"url\":\"latitude\",\"valueDecimal\":42.00462306215518},{\"url\":\"longitude\",\"valueDecimal\":-71.36086534446805}]}"],"line":["898 Bradtke Lodge"],"city":"North Attleborough","state":"MA","country":"US"}],"maritalStatus":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/v3-MaritalStatus","code":"M","display":"M"}],"text":"M"},"multipleBirthBoolean":false,"communication":[{"language":{"coding":[{"system":"urn:ietf:bcp:47","code":"en-US","display":"English"}],"text":"English"}}]}

     ] -> Take this and convert it to a bundle

     uPickle's ujson seems fairly lightweight
     */
    /*
     
     bundle.setType(Bundle.BundleType.SEARCHSET)
     bundle.setId(UUID.randomUUID().toString)
     bundle.setTimestamp(new Date())

     entry.setFullUrl(s"urn:uuid:${patient.getIdElement.getIdPart}")
     entry.setResource(patient)
     bundle.addEntry(entry)
     
     */
  }
}


/*
class QueryRunner {
  private val fhirContext: FhirContext = FhirContext.forR4()
  private val parser: IParser = fhirContext.newJsonParser()
  private val objectMapper = new ObjectMapper()

  def runQuery(queryInput: QueryInput): QueryOutput = {
    val startTime = System.currentTimeMillis()
    val bundle = runDatabaseQuery(queryInput.query, queryInput)
    QueryOutput(bundle, System.currentTimeMillis() - startTime)
  }

  private def runDatabaseQuery(query: String, queryInput: QueryInput): Bundle = {
    val connection: Connection = DatabaseConnectionPool.getConnection(queryInput.oboUser, queryInput.userToken)
    var resultSet: ResultSet = null

    val bundle = new Bundle()
    bundle.setType(Bundle.BundleType.SEARCHSET)
    bundle.setId(UUID.randomUUID().toString)
    bundle.setTimestamp(new Date())

    try {
      val statement = connection.createStatement()
      println(s"Executing SQL Query: $query")
      resultSet = statement.executeQuery(query)

      while (resultSet.next()) {
        val rawJson = resultSet.getString("Patient_JSON")

        println("🧪 Raw JSON from DB:")
        println(rawJson)

        try {
          val jsonNode = objectMapper.readTree(rawJson).asInstanceOf[ObjectNode]

          // Ensure "resourceType" is present
          if (!jsonNode.has("resourceType")) {
            println("⚠️ JSON missing resourceType – patching as 'Patient'")
            jsonNode.put("resourceType", "Patient")
          }

          // Recursively clean all stringified extensions
          fixStringifiedExtensions(jsonNode)

          val cleanedJson = objectMapper.writeValueAsString(jsonNode)

          println("🧼 Cleaned JSON with extensions fixed:")
          println(cleanedJson)

          // Only parse if valid
          if (cleanedJson.contains("\"resourceType\"")) {
            val patient = parser.parseResource(classOf[Patient], cleanedJson)

            val entry = new BundleEntryComponent()
            entry.setFullUrl(s"urn:uuid:${patient.getIdElement.getIdPart}")
            entry.setResource(patient)
            bundle.addEntry(entry)
          } else {
            println("❌ Skipping resource – still missing 'resourceType' after cleaning.")
          }

        } catch {
          case e: Exception =>
            println(s"❌ Error parsing Patient JSON: ${e.getMessage}")
            e.printStackTrace()
        }
      }
    } catch {
      case e: Exception =>
        println(s"Error executing query: ${e.getMessage}")
        e.printStackTrace()
    } finally {
      if (resultSet != null) resultSet.close()
      if (connection != null) connection.close()
    }

    bundle.setTotal(bundle.getEntry.size())
    bundle
  }
 }
 */
